BASE_KEYWORDS = [

# length
"meters-to-feet",
"meters-to-inches",
"meters-to-yards",
"meters-to-miles",
"meters-to-cm",
"meters-to-mm",
"meters-to-km",
"km-to-meters",
"km-to-miles",
"km-to-feet",
"km-to-yards",
"cm-to-inches",
"cm-to-feet",
"cm-to-meters",
"mm-to-inches",
"mm-to-feet",
"mm-to-meters",
"feet-to-meters",
"feet-to-inches",
"feet-to-yards",
"feet-to-miles",
"inches-to-cm",
"inches-to-feet",
"inches-to-meters",
"yards-to-feet",
"yards-to-meters",
"yards-to-miles",
"miles-to-km",
"miles-to-feet",
"miles-to-yards",

# weight
"kg-to-pounds",
"pounds-to-kg",
"kg-to-grams",
"grams-to-kg",
"kg-to-ounces",
"ounces-to-kg",
"grams-to-ounces",
"ounces-to-grams",
"pounds-to-ounces",
"ounces-to-pounds",
"tons-to-kg",
"kg-to-tons",
"grams-to-pounds",
"pounds-to-grams",
"mg-to-grams",
"grams-to-mg",

# volume
"liters-to-gallons",
"gallons-to-liters",
"liters-to-ml",
"ml-to-liters",
"liters-to-cups",
"cups-to-liters",
"liters-to-pints",
"pints-to-liters",
"gallons-to-cups",
"cups-to-gallons",
"gallons-to-pints",
"pints-to-gallons",

# speed
"kmh-to-mph",
"mph-to-kmh",
"kmh-to-ms",
"ms-to-kmh",
"mph-to-ms",
"ms-to-mph",
"knots-to-kmh",
"kmh-to-knots",
"knots-to-mph",
"mph-to-knots",

# temperature
"celsius-to-fahrenheit",
"fahrenheit-to-celsius",
"celsius-to-kelvin",
"kelvin-to-celsius",
"fahrenheit-to-kelvin",
"kelvin-to-fahrenheit",

# area
"square-meters-to-square-feet",
"square-feet-to-square-meters",
"acres-to-hectares",
"hectares-to-acres",
"square-meters-to-hectares",
"hectares-to-square-meters",
"square-km-to-hectares",
"hectares-to-square-km",

]
